---
- name: Restart selected production
  ansible.builtin.systemd_service:
    name: "{{ deepseek_service.name }}"
    daemon_reload: true
    state: restarted
  when: deepseek_service.auto_start | bool
